### ISSUE TITLE
Support for Helpdesk 4.x

### ISSUE THREAD

**Issue by alexhell** [darkstarSH/redmine_contacts_helpdesk_gpg#4]
I tried to install the plugin, but it aborted with 

`NameError: undefined method `receive' for class `HelpdeskMailer'`

Some ideas, what is broken?

Best,
alex

Environment:
  Redmine version                3.4.6.stable.17594
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               Mysql2
...                  
Redmine plugins:
  additionals                    2.0.15
  bestest_markdown_editor        1.1.0
  bestest_timer                  1.2.0
  redmine_agile                  1.4.7
  redmine_auto_resubmission      1.0.2
  redmine_checklists             3.1.11
  redmine_contacts               4.2.2
  redmine_contacts_helpdesk      4.0.0
  redmine_contacts_invoices      4.1.6
  redmine_custom_css             0.1.7
  redmine_drawio                 0.8.2
  redmine_fetch_email_attachments 2.0.2
  redmine_finance                2.1.4
  redmine_issue_attachments      1.0.4
  redmine_issue_templates        0.2.0
  redmine_more_code              1.0.0
  redmine_people                 1.4.0
  redmine_preview_inline         1.0.2
  redmine_products               2.0.5
  redmine_reporter               1.0.0
  redmine_shortcuts              0.1.0
  redmine_telegram_global        0.1
  vault                          0.3.9

**Comment by darkstarSH** [comment]
You're using "redmine_contacts_helpdesk 4.0.0".
Hmm, the last version that I successfully used with my plugin is 3.0.9.

May there's no method in HelpdeskMailer anymore?
I will have a look at the new version of the helpdesk plugin...

**Comment by thooge** [comment]
Same error here in my test environment.
Clean redmine with only redmine_contacts 4.2.3 and redmine_contacts_helpdesk 4.0.0 installed.
Seems there happened a big rework of the mailsystem between version 3.0.10 and 4.0.0.

**Comment by darkstarSH** [comment]
new release (0.0.9) now supports version 4.x of the Helpdesk plugin from RedmineUP
